name: Deploy Blazor Server

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify the version of .NET Core

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS
        run: |
          $destination = "\\\\185.165.119.63\\c$\\sites\\sadin.dev\\ui"
          New-PSDrive -Name S -PSProvider FileSystem -Root $destination -Credential (Get-Credential)
          Copy-Item -Path ./publish/* -Destination S:\ -Recurse -Force
          Remove-PSDrive -Name S
        env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs
